[build]
  command = "npm run build"  # or "yarn build"
  publish = "dist"  # Change this to 'dist', as Vite outputs to the 'dist' directory

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
